import './globals.css'
import { Montserrat } from 'next/font/google'
import Sidebar from '@/components/sidebar'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <div>
          <Sidebar children={children}/> // eslint-disable-line
        </div>
      </body>
    </html>
  )
}
